### ISSUE TITLE
Readme.md instructions inconsistent with repository state

### ISSUE THREAD

**Issue by kbempah** [SDNNetSim/sdn_simulator#37]
Installation instructions 2, 3, 5, and 6 do not accurately represent the current state of the repository.

**Comment by ryanmccann1024** [comment]
Hello, the inconsistency for instructions 2 and 3 make sense due to a renaming of the repository.

Could you be a little more specific about 5 and 6?

Thank you.

**Comment by kbempah** [comment]
*5. Navigate to the docs directory and generate the Sphinx documentation*:
![htmlerror](https://github.com/SDNNetSim/sdn_simulator/assets/84683652/95db6d86-ee48-420e-a4d8-2c366dc30000)
The Makefile does not have an `html` target.

*6. Finally, navigate to _build/html/ and open index.html in a browser of your choice to view the documentation.*
![step6](https://github.com/SDNNetSim/sdn_simulator/assets/84683652/19265f50-79da-4d47-bc74-c8e71ff11579)
Step 6 is not possible without building the `html` target.

**Comment by ryanmccann1024** [comment]
Would you mind verifying sphinx is installed? If so, what version?

**Comment by kbempah** [comment]
I do not have sphinx installed on my system. Is it installed as part of installation step 4 or as a separate installation?

**Comment by ryanmccann1024** [comment]
It should be installed in step 4

**Comment by kbempah** [comment]
I suggest we add an installation step urging future users/collaborators to verify the installation of Sphinx after performing step 4

**Comment by ryanmccann1024** [comment]
Typically pip will error check dependencies when using `pip install -r requirements.txt`.

Would you mind posting the output of the above command?

**Comment by kbempah** [comment]
sdn_simulator % ~> pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: networkx==3.2.1 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: numpy==1.26.3 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.26.3)
Requirement already satisfied: pylint==3.0.3 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: sphinx==7.2.6 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (7.2.6)
Requirement already satisfied: sphinx_rtd_theme==2.0.0 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.0.0)
Requirement already satisfied: pandas==2.2.0 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.2.0)
Requirement already satisfied: openpyxl==3.1.2 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: matplotlib==3.8.2 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (3.8.2)
Requirement already satisfied: seaborn==0.13.2 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (0.13.2)
Requirement already satisfied: stable-baselines3==2.2.1 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.2.1)
Requirement already satisfied: gymnasium==0.29.1 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.29.1)
Requirement already satisfied: scikit-learn==1.4.0 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (1.4.0)
Requirement already satisfied: dill>=0.2 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (0.3.8)
Requirement already satisfied: tomli>=1.1.0 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (2.0.1)
Requirement already satisfied: astroid<=3.1.0-dev0,>=3.0.1 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (3.0.3)
Requirement already satisfied: platformdirs>=2.2.0 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (4.2.0)
Requirement already satisfied: mccabe<0.8,>=0.6 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (0.7.0)
Requirement already satisfied: tomlkit>=0.10.1 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (0.12.4)
Requirement already satisfied: isort!=5.13.0,<6,>=4.2.5 in /home/kbempah/.local/lib/python3.10/site-packages (from pylint==3.0.3->-r requirements.txt (line 3)) (5.13.2)
Requirement already satisfied: sphinxcontrib-jsmath in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: Pygments>=2.14 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (2.17.2)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (1.1.10)
Requirement already satisfied: snowballstemmer>=2.0 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: imagesize>=1.3 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (1.4.1)
Requirement already satisfied: sphinxcontrib-qthelp in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (1.0.7)
Requirement already satisfied: requests>=2.25.0 in /usr/lib/python3/dist-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (2.25.1)
Requirement already satisfied: babel>=2.9 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (2.14.0)
Requirement already satisfied: sphinxcontrib-devhelp in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (1.0.6)
Requirement already satisfied: docutils<0.21,>=0.18.1 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (0.20.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (0.7.16)
Requirement already satisfied: packaging>=21.0 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (23.2)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (2.0.5)
Requirement already satisfied: Jinja2>=3.0 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (3.1.3)
Requirement already satisfied: sphinxcontrib-applehelp in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx==7.2.6->-r requirements.txt (line 4)) (1.0.8)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in /home/kbempah/.local/lib/python3.10/site-packages (from sphinx_rtd_theme==2.0.0->-r requirements.txt (line 5)) (4.1)
Requirement already satisfied: tzdata>=2022.7 in /home/kbempah/.local/lib/python3.10/site-packages (from pandas==2.2.0->-r requirements.txt (line 6)) (2024.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas==2.2.0->-r requirements.txt (line 6)) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kbempah/.local/lib/python3.10/site-packages (from pandas==2.2.0->-r requirements.txt (line 6)) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /home/kbempah/.local/lib/python3.10/site-packages (from openpyxl==3.1.2->-r requirements.txt (line 7)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /home/kbempah/.local/lib/python3.10/site-packages (from matplotlib==3.8.2->-r requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib==3.8.2->-r requirements.txt (line 8)) (2.4.7)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/kbempah/.local/lib/python3.10/site-packages (from matplotlib==3.8.2->-r requirements.txt (line 8)) (1.4.5)
Requirement already satisfied: contourpy>=1.0.1 in /home/kbempah/.local/lib/python3.10/site-packages (from matplotlib==3.8.2->-r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/kbempah/.local/lib/python3.10/site-packages (from matplotlib==3.8.2->-r requirements.txt (line 8)) (4.49.0)
Requirement already satisfied: pillow>=8 in /usr/lib/python3/dist-packages (from matplotlib==3.8.2->-r requirements.txt (line 8)) (9.0.1)
Requirement already satisfied: torch>=1.13 in /home/kbempah/.local/lib/python3.10/site-packages (from stable-baselines3==2.2.1->-r requirements.txt (line 10)) (2.2.1)
Requirement already satisfied: cloudpickle in /home/kbempah/.local/lib/python3.10/site-packages (from stable-baselines3==2.2.1->-r requirements.txt (line 10)) (3.0.0)
Requirement already satisfied: typing-extensions>=4.3.0 in /home/kbempah/.local/lib/python3.10/site-packages (from gymnasium==0.29.1->-r requirements.txt (line 11)) (4.10.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /home/kbempah/.local/lib/python3.10/site-packages (from gymnasium==0.29.1->-r requirements.txt (line 11)) (0.0.4)
Requirement already satisfied: scipy>=1.6.0 in /home/kbempah/.local/lib/python3.10/site-packages (from scikit-learn==1.4.0->-r requirements.txt (line 12)) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in /home/kbempah/.local/lib/python3.10/site-packages (from scikit-learn==1.4.0->-r requirements.txt (line 12)) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/kbempah/.local/lib/python3.10/site-packages (from scikit-learn==1.4.0->-r requirements.txt (line 12)) (3.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/kbempah/.local/lib/python3.10/site-packages (from Jinja2>=3.0->sphinx==7.2.6->-r requirements.txt (line 4)) (2.1.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.0->-r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.1.105)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.1.3.1)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.1.0.106)
Requirement already satisfied: sympy in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (1.12)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (11.0.2.54)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (2.2.0)
Requirement already satisfied: fsspec in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (2024.2.0)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (8.9.2.26)
Requirement already satisfied: filelock in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (3.13.1)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (10.3.2.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /home/kbempah/.local/lib/python3.10/site-packages (from torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (2.19.3)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/kbempah/.local/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (12.3.101)
Requirement already satisfied: mpmath>=0.19 in /home/kbempah/.local/lib/python3.10/site-packages (from sympy->torch>=1.13->stable-baselines3==2.2.1->-r requirements.txt (line 10)) (1.3.0)

**Comment by ryanmccann1024** [comment]
```
Requirement already satisfied: sphinx==7.2.6 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (7.2.6)
Requirement already satisfied: sphinx_rtd_theme==2.0.0 in /home/kbempah/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.0.0)
```

It looks like sphinx was successfully installed, would you mind running the command again to see if it works?

**Comment by kbempah** [comment]
I see what's going on. I recently changed shells to zsh and had not updated my path variable with the directories where sphinx and the other dependencies were installed.

**Comment by kbempah** [comment]
I got it to work on MacOS, although I had to create a virtual environment in order to install the dependencies with pip3

**Comment by ryanmccann1024** [comment]
Awesome! I'll close this issue.

I believe python3.9 or greater is required, we can add it to the requirements.
